Send rebase message to all issues waiting or in progress
moodlehq/moodle-local_ci pull request #237
Opened 2021-05-21 15:41 UTC by sarjona

This script will send now 2 different messages:

- Issues under candidate queue, the standard message. It's the one
that existed before under the altcomment, that has been renamed to
altcommentcandidate.
- Issues under current queue, the new standard message, to explain
it will be kept under integration one more week. The standard
message can be overridden by altcommentcurrent.

Filter https://tracker.moodle.org/issues/?filter=22610 has been created (its equivalent in next.tracker is 22700).

2021-05-21 17:01 UTC, stronk7 requested changes
Just 3 comments and 2 of them requiring changes.

About the new filter also "spamming" issues in progress... as commented, ok here, let's see if it disturbs us or no.

2021-05-21 18:20 UTC, sarjona commented on tracker_automations/send_rebase_message/send_rebase_message.sh
> +    TIA and ciao :-)"}
I've tested it in https://tracker.next.moodle.org/browse/MDL-71691 and, as you'll see, it's displayed properly :-) 
So in order to make the code more readable, I'll leave these spaces there... Is that ok?

2021-05-21 18:22 UTC, sarjona commented on tracker_automations/send_rebase_message/send_rebase_message.sh
> +           --search "filter = 22610" \
I feel that's better to put the comment too when issues are in progress (a rebase should never hurt...). But yes, let's see how it works and, if required, as you said, we can easily change the filter :-)

2021-05-21 18:23 UTC, sarjona commented on tracker_automations/send_rebase_message/send_rebase_message.sh
> +altcommentcandidate=${altcommentcandidates}
Well spotted... I've realised about that and removed the extra "s" from most of the places... but I missed a couple of them! :-S My apologies for the inconvenience

2021-05-21 18:26 UTC, sarjona commented
Hi Eloy!

Thanks a lot for reviewing the patch! I've fixed one of the issues and leave the other as it is because it's working properly (the spaces before "TIA..."). As it is working I've preferred not to removing those spaces (because without them, the code will look weird :-S ). 

Please, let me know if any other change is required :-)

2021-05-21 19:09 UTC, stronk7 commented on tracker_automations/send_rebase_message/send_rebase_message.sh
> +    TIA and ciao :-)"}
Perfect!

2021-05-21 19:09 UTC, stronk7 commented on tracker_automations/send_rebase_message/send_rebase_message.sh
> +           --search "filter = 22610" \
Agreed!

2021-05-21 19:11 UTC, stronk7 commented on tracker_automations/send_rebase_message/send_rebase_message.sh
> +altcommentcandidate=${altcommentcandidates}
Heh,

I must be missing something here, the line now says:
```
altcommentcandidate=${altcommentcandidate}
```

That's setting a variable to itself (aka, in PHP: `$var = $var` , I'm pretty sure it does nothing!

2021-05-23 17:55 UTC, sarjona commented on tracker_automations/send_rebase_message/send_rebase_message.sh
> +altcommentcandidate=${altcommentcandidates}
Ups... You're right! I've removed it so now I think the patch should be ready :-)

2021-05-24 10:13 UTC, stronk7 approved these changes
I like it™

2021-05-24 12:21 UTC, merged

2021-05-24 12:21 UTC, stronk7 commented
Merged, thanks!